// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzsJWyc3RyndnxeE9rvEMSksDpqQUZHx0',
    appId: '1:305755168371:web:37a1c2085e7bef1ce41406',
    messagingSenderId: '305755168371',
    projectId: 'agro-conecta-887df',
    authDomain: 'agro-conecta-887df.firebaseapp.com',
    storageBucket: 'agro-conecta-887df.firebasestorage.app',
    measurementId: 'G-G3N5MTDL8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClygACNYQDjp5Y5BM8ECB90pgI6QCDuWU',
    appId: '1:305755168371:android:40ecc1528bd4f04ee41406',
    messagingSenderId: '305755168371',
    projectId: 'agro-conecta-887df',
    storageBucket: 'agro-conecta-887df.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCox-4BCJg02nvmKZFcjiH8ekryrvW5bnM',
    appId: '1:305755168371:ios:b17612b4df845483e41406',
    messagingSenderId: '305755168371',
    projectId: 'agro-conecta-887df',
    storageBucket: 'agro-conecta-887df.firebasestorage.app',
    iosClientId: '305755168371-6ctotdf050rvo11kcfc6alsasekg02if.apps.googleusercontent.com',
    iosBundleId: 'com.example.agroFields',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCox-4BCJg02nvmKZFcjiH8ekryrvW5bnM',
    appId: '1:305755168371:ios:b17612b4df845483e41406',
    messagingSenderId: '305755168371',
    projectId: 'agro-conecta-887df',
    storageBucket: 'agro-conecta-887df.firebasestorage.app',
    iosClientId: '305755168371-6ctotdf050rvo11kcfc6alsasekg02if.apps.googleusercontent.com',
    iosBundleId: 'com.example.agroFields',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzsJWyc3RyndnxeE9rvEMSksDpqQUZHx0',
    appId: '1:305755168371:web:aa28b33dad08a729e41406',
    messagingSenderId: '305755168371',
    projectId: 'agro-conecta-887df',
    authDomain: 'agro-conecta-887df.firebaseapp.com',
    storageBucket: 'agro-conecta-887df.firebasestorage.app',
    measurementId: 'G-S42YTLHKJM',
  );
}
